# Generated by Django 5.1.4 on 2026-01-20 06:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='SDG number from 1 to 17', unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)])),
                ('name', models.CharField(help_text='Name of the SDG', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the SDG')),
                ('icon_url', models.URLField(blank=True, help_text='URL to SDG icon', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SDG Goal',
                'verbose_name_plural': 'SDG Goals',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the activity', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('activity_type', models.CharField(choices=[('research', 'Research'), ('project', 'Project'), ('curriculum', 'Curriculum'), ('outreach', 'Outreach')], help_text='Type of activity', max_length=20)),
                ('evidence_file', models.FileField(blank=True, help_text='Supporting evidence (PDF, image, etc.)', null=True, upload_to='evidence/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_classified', models.BooleanField(default=False, help_text='Whether this activity has been classified by AI')),
                ('lead_author', models.ForeignKey(help_text='User who uploaded/created this activity', on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(help_text='Name of the university', max_length=255)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('score', models.FloatField(help_text='Annual SDG performance score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_activities', models.IntegerField(default=0, help_text='Total activities for this SDG in the year')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sdg_goal', models.ForeignKey(help_text='Related SDG goal', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='impact_tracker.sdggoal')),
            ],
            options={
                'verbose_name': 'Institution Metric',
                'verbose_name_plural': 'Institution Metrics',
                'ordering': ['-year', 'sdg_goal__number'],
                'unique_together': {('university_name', 'year', 'sdg_goal')},
            },
        ),
        migrations.CreateModel(
            name='SDGImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Relevance score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('justification', models.TextField(help_text='AI-generated reasoning for the impact score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(help_text='Related activity', on_delete=django.db.models.deletion.CASCADE, related_name='sdg_impacts', to='impact_tracker.activity')),
                ('sdg_goal', models.ForeignKey(help_text='Related SDG goal', on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='impact_tracker.sdggoal')),
            ],
            options={
                'verbose_name': 'SDG Impact',
                'verbose_name_plural': 'SDG Impacts',
                'ordering': ['-score'],
                'unique_together': {('activity', 'sdg_goal')},
            },
        ),
    ]
