# Generated by Django 5.1.4 on 2026-01-21 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='authors',
            field=models.TextField(blank=True, help_text='Authors of the activity (for scraped content)', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL to the original external source of the activity', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_scraped',
            field=models.BooleanField(default=False, help_text='Whether this activity was scraped from an external source'),
        ),
        migrations.AddField(
            model_name='activity',
            name='original_publication_date',
            field=models.DateField(blank=True, help_text='Original publication date of the activity', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('research', 'Research'), ('project', 'Project'), ('curriculum', 'Curriculum'), ('outreach', 'Outreach'), ('publication', 'Publication')], help_text='Type of activity', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lead_author',
            field=models.ForeignKey(blank=True, help_text='User who uploaded/created this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
