# Generated by Django 5.1.4 on 2026-01-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_tracker', '0002_activity_authors_activity_external_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='impact_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='sdgs',
            field=models.ManyToManyField(blank=True, help_text='Which SDGs this activity is related to.', to='impact_tracker.sdggoal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Published', 'Published')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='sdggoal',
            name='color_code',
            field=models.CharField(blank=True, help_text='Hex color code for the SDG (e.g., #E5243B)', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('Project', 'Project'), ('Publication', 'Publication')], help_text='Type of activity', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='authors',
            field=models.TextField(blank=True, help_text='Legacy field for scraped authors (dc:creator)', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='external_url',
            field=models.URLField(blank=True, help_text='URL to the original external source of the activity (Evidence Link)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='lead_author',
            field=models.ForeignKey(blank=True, help_text='Legacy user who uploaded/created this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Job title, e.g., Professor, Lecturer', max_length=100, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researchers', to='impact_tracker.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The researcher who authored this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='impact_tracker.researcher'),
        ),
    ]
