# Generated by Django 5.1.4 on 2026-01-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact_tracker', '0003_department_activity_impact_summary_activity_sdgs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the institution (e.g., Strathmore, UoN)', max_length=255, unique=True)),
                ('total_sdg_score', models.IntegerField(default=0, help_text='An aggregated SDG score for comparison.')),
                ('projects_count', models.IntegerField(default=0)),
                ('publications_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benchmark Institution',
                'verbose_name_plural': 'Benchmark Institutions',
                'ordering': ['name'],
            },
        ),
    ]
